### create Company(ADMIN)
POST localhost:8080/company/create
#Authorization:
Content-Type: application/json

{
  "name": "Asaka Bank",
  "address": "Buxoro",
  "contact": "HUMO",
  "visible": false,
  "role": "BANK",
  "phoneNummber": "+998944443322",
  "password": "9860"
}

### update Company(Admin)
PUT localhost:8080/company/update/1
#Authorization:
#Accept-Language:
Content-Type: application/json

{
  "address": "Toshkent",
  "contact": "UzCard",
  "password": "8600"
}